# Generated by Django 5.2.16 on 2026-07-21 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtsp_url', models.TextField(help_text='Full RTSP URL, including credentials when required.', validators=[django.core.validators.URLValidator(schemes=('rtsp', 'rtsps'))], verbose_name='RTSP connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
