# Generated by Django 5.2.16 on 2026-07-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDetectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_history', models.JSONField(blank=True, default=list)),
                ('stable_counts', models.JSONField(blank=True, default=dict)),
                ('current_counts', models.JSONField(blank=True, default=dict)),
                ('boxes', models.JSONField(blank=True, default=list)),
                ('frame_number', models.PositiveBigIntegerField(default=0)),
                ('inference_ms', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection_state', to='vision.videofeed')),
            ],
            options={
                'verbose_name': 'feed detection state',
                'verbose_name_plural': 'feed detection states',
            },
        ),
    ]
