# Generated by Django 5.2.16 on 2026-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_feeddetectionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofeed',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Include this feed in the shared YOLO detection worker.', verbose_name='detection enabled'),
        ),
    ]
