# Generated by Django 5.2.16 on 2026-07-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_videofeed_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddetectionstate',
            name='worker_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('detecting', 'Detecting')], default='waiting', max_length=20),
        ),
    ]
